/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.97
 * Generated at: 2024-11-12 02:13:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730098803747L));
    _jspx_dependants.put("jar:file:/D:/springwork/spring_WEB/src/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/www/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <title>Document</title>\n");
      out.write("</head>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("  integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("  integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("  body {\n");
      out.write("    margin: 0px;\n");
      out.write("    width: 1920px;\n");
      out.write("    height: 1024px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #userinfo {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 1000px;\n");
      out.write("    height: 50px;\n");
      out.write("    /*  background-color: aqua;*/\n");
      out.write("    top: 40px;\n");
      out.write("    left: 1700px;\n");
      out.write("    position: absolute;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #header {\n");
      out.write("    width: 1920px;\n");
      out.write("    height: 100px;\n");
      out.write("    /* background-color: rgb(98, 139, 253);*/\n");
      out.write("    padding-top: 20px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    float: left;\n");
      out.write("    /* display: flex;*/\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .header_20 input[type=text] {\n");
      out.write("    width: 500px;\n");
      out.write("    height: 32px;\n");
      out.write("    font-size: 15px;\n");
      out.write("    border: solid 1px gray;\n");
      out.write("    border-radius: 15px;\n");
      out.write("    outline: none;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    background-color: rgb(233, 233, 233);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .header_10 {\n");
      out.write("    width: 400px;\n");
      out.write("    height: 40px;\n");
      out.write("    /* border: 1px solid;*/\n");
      out.write("    margin: 0px auto;\n");
      out.write("    text-align: center;\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .header_20 {\n");
      out.write("    padding-top: 5px;\n");
      out.write("    width: 1500px;\n");
      out.write("    height: 40px;\n");
      out.write("    /* border: 1px solid;*/\n");
      out.write("    margin: 0px auto;\n");
      out.write("    text-align: center;\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .header_10 h2 {\n");
      out.write("    display: inline;\n");
      out.write("    color: green;\n");
      out.write("    font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #nav {\n");
      out.write("    width: 1920px;\n");
      out.write("    height: 60px;\n");
      out.write("    float: left;\n");
      out.write("    border-bottom: 1px solid;\n");
      out.write("    font-size: larger;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  /*\n");
      out.write("    #nav ul li{\n");
      out.write("        color:black;\n");
      out.write("    }\n");
      out.write("     #nav ul li:hover{\n");
      out.write("        background-color: aqua;\n");
      out.write("    } */\n");
      out.write("  /*   ul {\n");
      out.write("*/\n");
      out.write("  /*   border: 1px solid;\n");
      out.write("        margin-top: 3px;\n");
      out.write("    }*/\n");
      out.write("  ul li {\n");
      out.write("    display: inline-block;\n");
      out.write("    width: 120px;\n");
      out.write("    /*   border: 1px solid;*/\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #mainsection {\n");
      out.write("    width: 80%;\n");
      out.write("    height: 900px;\n");
      out.write("    /*  border: 1px dotted;*/\n");
      out.write("    float: left;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #mainsection_01 {\n");
      out.write("    width: 80%;\n");
      out.write("    height: 300px;\n");
      out.write("    /*   border: 1px solid;\n");
      out.write("    /*    background-color: red;*/\n");
      out.write("    margin: 0px auto;\n");
      out.write("    text-align: center;\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #asidelogin {\n");
      out.write("    width: 20%;\n");
      out.write("    height: 500px;\n");
      out.write("    /* border: 1px solid;*/\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .subject {\n");
      out.write("    display: inline-block;\n");
      out.write("    font-size: larger;\n");
      out.write("    margin-bottom: 5px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #login {\n");
      out.write("    background-color: darkcyan;\n");
      out.write("    padding-top: 15px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("    color: white;\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #login,\n");
      out.write("  #loginup,\n");
      out.write("  #logindown {\n");
      out.write("    width: 250px;\n");
      out.write("    height: 50px;\n");
      out.write("    text-align: center;\n");
      out.write("    vertical-align: middle;\n");
      out.write("    margin: 0px auto;\n");
      out.write("\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #loginbox {\n");
      out.write("    margin-top: 30px;\n");
      out.write("    box-sizing: border-box;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #infosection {\n");
      out.write("    width: 1920px;\n");
      out.write("    height: 150px;\n");
      out.write("    /* border: 1px solid;*/\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .infosetion_card {\n");
      out.write("    width: 360px;\n");
      out.write("    height: 150px;\n");
      out.write("    margin-left: 20px;\n");
      out.write("    /* background-color: yellow;*/\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #footer {\n");
      out.write("    width: 1920px;\n");
      out.write("    text-align: center;\n");
      out.write("    font-size: larger;\n");
      out.write("    /* border: 1px solid;*/\n");
      out.write("    float: left;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("<style>\n");
      out.write("  .dropdown {\n");
      out.write("    display: inline-block;\n");
      out.write("    position: relative;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  #btn01,\n");
      out.write("  #btn02,\n");
      out.write("  #btn03,\n");
      out.write("  #btn04,\n");
      out.write("  #btn05 {\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    padding: 3px 30px;\n");
      out.write("    font-size: 18px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    display: inline-block;\n");
      out.write("    background-color: white;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  button:hover {\n");
      out.write("    background-color: #ddd;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .dropdown-options {\n");
      out.write("    display: none;\n");
      out.write("    position: absolute;\n");
      out.write("    overflow: auto;\n");
      out.write("    background-color: #fff;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    box-shadow: 0px 10px 10px 0px rgba(0, 0, 0, 0.4);\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .dropdown:hover .dropdown-options {\n");
      out.write("    display: block;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .dropdown-options a {\n");
      out.write("    display: block;\n");
      out.write("    color: #000000;\n");
      out.write("    padding: 5px;\n");
      out.write("    text-decoration: none;\n");
      out.write("    padding: 20px 40px;\n");
      out.write("  }\n");
      out.write("\n");
      out.write("  .dropdown-options a:hover {\n");
      out.write("    color: #0a0a23;\n");
      out.write("    background-color: #ddd;\n");
      out.write("    border-radius: 5px;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("<style>\n");
      out.write("  /*boot strap에서 마우스 올려 놓으면 메뉴 자동 펼치기 추가 코드 */\n");
      out.write("  nav li.dropdown:hover>ul.dropdown-menu {\n");
      out.write("    display: block;\n");
      out.write("    margin: 0;\n");
      out.write("  }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <div id=\"header\">\n");
      out.write("    <div class=\"header_10\">\n");
      out.write("      <h2>KimTeacher Lap</h2>\n");
      out.write("      <h5>Programers</h5>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"header_20\">\n");
      out.write("      <!--<form>\n");
      out.write("                <input type=\"text\" name=\"searchword\" size=\"70\">\n");
      out.write("                <input type=\"submit\" value=\"Search\">\n");
      out.write("            </form>-->\n");
      out.write("    </div>\n");
      out.write("    <div id=\"userinfo\">\n");
      out.write("      <div>\n");
      out.write("        <p><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-bug\"\n");
      out.write("            viewBox=\"0 0 16 16\">\n");
      out.write("            <path\n");
      out.write("              d=\"M4.355.522a.5.5 0 0 1 .623.333l.291.956A4.979 4.979 0 0 1 8 1c1.007 0 1.946.298 2.731.811l.29-.956a.5.5 0 1 1 .957.29l-.41 1.352A4.985 4.985 0 0 1 13 6h.5a.5.5 0 0 0 .5-.5V5a.5.5 0 0 1 1 0v.5A1.5 1.5 0 0 1 13.5 7H13v1h1.5a.5.5 0 0 1 0 1H13v1h.5a1.5 1.5 0 0 1 1.5 1.5v.5a.5.5 0 1 1-1 0v-.5a.5.5 0 0 0-.5-.5H13a5 5 0 0 1-10 0h-.5a.5.5 0 0 0-.5.5v.5a.5.5 0 1 1-1 0v-.5A1.5 1.5 0 0 1 2.5 10H3V9H1.5a.5.5 0 0 1 0-1H3V7h-.5A1.5 1.5 0 0 1 1 5.5V5a.5.5 0 0 1 1 0v.5a.5.5 0 0 0 .5.5H3c0-1.364.547-2.601 1.432-3.503l-.41-1.352a.5.5 0 0 1 .333-.623zM4 7v4a4 4 0 0 0 3.5 3.97V7H4zm4.5 0v7.97A4 4 0 0 0 12 11V7H8.5zM12 6a3.989 3.989 0 0 0-1.334-2.982A3.983 3.983 0 0 0 8 2a3.983 3.983 0 0 0-2.667 1.018A3.989 3.989 0 0 0 4 6h8z\" />\n");
      out.write("          </svg> <span id=\"kk\">현재사용자 : Guest</span></p>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("      li {\n");
      out.write("        color: white;\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("  </div>\n");
      out.write("  <div id=\"nav\">\n");
      out.write("    <nav class=\"navbar navbar-expand-lg \" style=\"background-color: #89bce6;\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\"></a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("          aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("          <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"#\"> </a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"./index.html\">Home</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link\" href=\"#\">Lecture</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item dropdown\">\n");
      out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\"\n");
      out.write("                aria-expanded=\"false\">\n");
      out.write("                Study\n");
      out.write("              </a>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"./java.html\">java</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Another action</a></li>\n");
      out.write("                <li>\n");
      out.write("                  <hr class=\"dropdown-divider\">\n");
      out.write("                </li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"board\">게시판</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">뉴스</a>\n");
      out.write("            </li>\n");
      out.write("            <li class=\"nav-item\">\n");
      out.write("              <a class=\"nav-link active\" aria-current=\"page\" href=\"#\">취업정보</a>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("          <form class=\"d-flex\" role=\"search\">\n");
      out.write("            <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("            <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!--      <ul>\n");
      out.write("            <li><div class=\"dropdown\">\n");
      out.write("                <button id=\"btn01\">Laps</button>\n");
      out.write("                <div class=\"dropdown-options\">\n");
      out.write("                  <a href=\"#\">Dashboard</a>\n");
      out.write("                  <a href=\"#\">Setting</a>\n");
      out.write("                  <a href=\"#\">Logout</a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            <li><div class=\"dropdown\">\n");
      out.write("                <button id=\"btn02\">DataBase</button>\n");
      out.write("                <div class=\"dropdown-options\">\n");
      out.write("                  <a href=\"#\">Dashboar2d</a>\n");
      out.write("                  <a href=\"#\">Setting2</a>\n");
      out.write("                  <a href=\"#\">Logou2t</a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            <li><div class=\"dropdown\">\n");
      out.write("                <button id=\"btn03\">FrontEnd</button>\n");
      out.write("                <div class=\"dropdown-options\">\n");
      out.write("                  <a href=\"#\">Dashboard</a>\n");
      out.write("                  <a href=\"#\">Setting</a>\n");
      out.write("                  <a href=\"#\">Logout</a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            <li><div class=\"dropdown\">\n");
      out.write("                <button id=\"btn04\">BackEnd</button>\n");
      out.write("                <div class=\"dropdown-options\">\n");
      out.write("                  <a href=\"#\">Dashboard</a>\n");
      out.write("                  <a href=\"#\">Setting</a>\n");
      out.write("                  <a href=\"#\">Logout</a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("            <li><div class=\"dropdown\">\n");
      out.write("                <button id=\"btn05\">Lecture</button>\n");
      out.write("                <div class=\"dropdown-options\">\n");
      out.write("                  <a href=\"#\">Dashboard</a>\n");
      out.write("                  <a href=\"#\">Setting</a>\n");
      out.write("                  <a href=\"#\">Logouts</a>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    -->\n");
      out.write("  </div>\n");
      out.write("  <div id=\"mainsection\">\n");
      out.write("    <style>\n");
      out.write("      #mainsection_left {\n");
      out.write("        /*  display: inline-block;*/\n");
      out.write("        float: left;\n");
      out.write("        width: 300px;\n");
      out.write("        height: 500px;\n");
      out.write("        /*    border: 1px solid;*/\n");
      out.write("        padding: 20px 20px 20px 30px;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("    <div id=\"mainsection_left\">\n");
      out.write("\n");
      out.write("      <div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical button group\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Button</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Button</button>\n");
      out.write("        <div class=\"btn-group\" role=\"group\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Dropdown\n");
      out.write("          </button>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"btn-group dropstart\" role=\"group\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Dropdown\n");
      out.write("          </button>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"btn-group dropend\" role=\"group\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Dropdown\n");
      out.write("          </button>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"btn-group dropup\" role=\"group\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary dropdown-toggle\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Dropdown\n");
      out.write("          </button>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Dropdown link</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"mainsection_01\">\n");
      out.write("      <div>\n");
      out.write("        <div id=\"carouselExampleCaptions\" class=\"carousel slide\">\n");
      out.write("          <div class=\"carousel-indicators\">\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\"\n");
      out.write("              aria-current=\"true\" aria-label=\"Slide 1\"></button>\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\"\n");
      out.write("              aria-label=\"Slide 2\"></button>\n");
      out.write("            <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\"\n");
      out.write("              aria-label=\"Slide 3\"></button>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"carousel-inner\">\n");
      out.write("            <div class=\"carousel-item active\">\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/indexmain.jpg\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                <h5>올바른 개발자 </h5>\n");
      out.write("                <p>첫 시작은 올바르게</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"carousel-item\">\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/java.PNG\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                <h5>Second slide label</h5>\n");
      out.write("                <p>Some representative placeholder content for the second slide.</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"carousel-item\">\n");
      out.write("              <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/js.PNG\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("              <div class=\"carousel-caption d-none d-md-block\">\n");
      out.write("                <h5>Third slide label</h5>\n");
      out.write("                <p>Some representative placeholder content for the third slide.</p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\n");
      out.write("            data-bs-slide=\"prev\">\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("            <span class=\"visually-hidden\">Previous</span>\n");
      out.write("          </button>\n");
      out.write("          <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\"\n");
      out.write("            data-bs-slide=\"next\">\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("            <span class=\"visually-hidden\">Next</span>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div id=\"asidelogin\">\n");
      out.write("    <div id=\"loginbox\">\n");
      out.write("      <div id=\"loginup\">\n");
      out.write("        KimTeacher Laps에 참여하세요\n");
      out.write("      </div>\n");
      out.write("      <div id=\"login\" data-bs-toggle=\"modal\" data-bs-target=\"#loginModal\">\n");
      out.write("        KimTeacher 로그인\n");
      out.write("      </div>\n");
      out.write("      <div id=\"logindown\">\n");
      out.write("        <br>\n");
      out.write("        <button type=\"button\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\n");
      out.write("          회원가입\n");
      out.write("        </button>\n");
      out.write("        <button type=\"button\">아이디/비빌번호찾기</button>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <style>\n");
      out.write("        #news {\n");
      out.write("          border: 1px solid;\n");
      out.write("          display: inline-block;\n");
      out.write("          width: 100%;\n");
      out.write("          height: 300px;\n");
      out.write("          margin: 0px auto;\n");
      out.write("          border-radius: 5%;\n");
      out.write("          border-color: rgb(196, 193, 193);\n");
      out.write("          background-color: white;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #talks {\n");
      out.write("          border: 1px solid;\n");
      out.write("          display: inline-block;\n");
      out.write("          width: 100%;\n");
      out.write("          height: 150px;\n");
      out.write("          margin: 0px auto;\n");
      out.write("          border-radius: 5%;\n");
      out.write("          border-color: rgb(196, 193, 193);\n");
      out.write("          background-color: white;\n");
      out.write("        }\n");
      out.write("      </style>\n");
      out.write("      <br>\n");
      out.write("      <div id=\"news\">\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/img/we.PNG\">\n");
      out.write("      </div>\n");
      out.write("      <div id=\"talks\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div id=\"infosection\">\n");
      out.write("    <div class=\"infosetion_card\">\n");
      out.write("      <h3> Java </h3>\n");
      out.write("      <hr>\n");
      out.write("      <p> 객체지향언어 자바는 프로그래밍 실력향상에 좋은 언어이다</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"infosetion_card\">\n");
      out.write("      <h3> Spring </h3>\n");
      out.write("      <hr>\n");
      out.write("      <p> 웹개발에서 Spring은 필수적인 요소이다. 프레임워크를 구성을 이해하자</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"infosetion_card\">\n");
      out.write("      <h3> JavaScript</h3>\n");
      out.write("      <hr>\n");
      out.write("      <p>자바스크립트는 html 태그를 선택하여 동적인 효과를 가져다 주며 반응형 웹에서 많이 사용한다.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"infosetion_card\">\n");
      out.write("      <h3> JavaScript</h3>\n");
      out.write("      <hr>\n");
      out.write("      <p>자바스크립트는 html 태그를 선택하여 동적인 효과를 가져다 주며 반응형 웹에서 많이 사용한다.</p>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"infosetion_card\">\n");
      out.write("      <h3> JavaScript</h3>\n");
      out.write("      <hr>\n");
      out.write("      <p>자바스크립트는 html 태그를 선택하여 동적인 효과를 가져다 주며 반응형 웹에서 많이 사용한다.</p>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("  <div id=\"footer\">\n");
      out.write("    <hr>\n");
      out.write("    김티처 tel. 010-9407-8767\n");
      out.write("  </div>\n");
      out.write("  <!-- Modal -->\n");
      out.write("  <form action=\"join\" method=\"post\">\n");
      out.write("  <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">회원가입</h1>\n");
      out.write("          <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <span class=\"input-group-text\" id=\"basic-addon1\">ID</span>\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Username\" aria-label=\"Username\"\n");
      out.write("              aria-describedby=\"basic-addon1\" name=\"id\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <span class=\"input-group-text\" id=\"basic-addon1\">PASS</span>\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Pass\" aria-label=\"Username\"\n");
      out.write("              aria-describedby=\"basic-addon1\" name=\"pass\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <span class=\"input-group-text\" id=\"basic-addon1\">TEL</span>\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"tel\" aria-label=\"Username\"\n");
      out.write("              aria-describedby=\"basic-addon1\" name=\"tel\">\n");
      out.write("          </div>\n");
      out.write("          <div class=\"input-group mb-3\">\n");
      out.write("            <span class=\"input-group-text\" id=\"basic-addon1\">EMAIL</span>\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"E-mail\" aria-label=\"Username\"\n");
      out.write("              aria-describedby=\"basic-addon1\" name=\"email\">\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"submit\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Save</button>\n");
      out.write("          <button type=\"button\" class=\"btn btn-primary\" data-bs-dismiss=\"modal\">Cancel</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  </form>\n");
      out.write("  <div>\n");
      out.write("    <!-- Modal -->\n");
      out.write("    <!-- Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel1\" aria-hidden=\"true\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("          <div class=\"modal-header\">\n");
      out.write("            <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel1\">로그인</h1>\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-body\">\n");
      out.write("            <div class=\"input-group mb-3\">\n");
      out.write("              <span class=\"input-group-text\" id=\"basic-addon1\">ID</span>\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Username\" aria-label=\"Username\"\n");
      out.write("                aria-describedby=\"basic-addon1\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"input-group mb-3\">\n");
      out.write("              <span class=\"input-group-text\" id=\"basic-addon1\">PASS</span>\n");
      out.write("              <input type=\"text\" class=\"form-control\" placeholder=\"Pass\" aria-label=\"Username\"\n");
      out.write("                aria-describedby=\"basic-addon1\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("              <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">login</button>\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary \" data-bs-dismiss=\"modal\">Cancel</button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div>\n");
      out.write("        <!-- Modal -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("<<script type=\"text/javascript\">\n");
      out.write("<!--\n");
      out.write("	\n");
      out.write("//-->\n");
      out.write("	\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
